version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    image: ghcr.io/example/restohub-api:latest
    depends_on: [db]
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    ports:
      - "${API_PORT:-8080}:8080"
  web:
    image: ghcr.io/example/restohub-web:latest
    depends_on: [api]
    ports:
      - "${WEB_PORT:-5173}:5173"
volumes:
  dbdata: {}
